### ISSUE TITLE
Preview window backcolor follow VSCode dark theme

### ISSUE THREAD

**Issue by xrq1051** [urin/vscode-web-visual-editor#10]
Under the vscode dark theme, the preview interface of the plugin has also become a dark background, resulting in some components being unable to see clearly, according to my understanding, the preview interface of the plugin should be the same as the background color of the actual web page when it is opened, rather than the background color of the development tool

![1](https://github.com/user-attachments/assets/3cf216af-8cc5-4ff6-a9d8-04f379510611)

**Comment by urin** [comment]
The default background color is not explicitly defined in the pure specification and is naturally considered transparent.  

Therefore, if you create HTML without explicitly specifying a background color for the `html` or `body` elements, the background color may vary depending on the user's environment.  

However, since most modern browsers default to a white background, I prioritized convenience and [changed the default background color from transparent to white](https://github.com/urin/vscode-web-visual-editor/commit/14e67fdd01393676faf72b53ed97fd243d9dd7cb#diff-a5611d9f60261fea2c2252bb4936aaae06674cb86636cc48a2805b6896035b5eR320-R323).
