### ISSUE TITLE
[Question] Does this also supports HTML inside PHP? 

### ISSUE THREAD

**Issue by 0Chan-smc** [urin/vscode-web-visual-editor#6]
When I installed this extension and I couldn't find the 'Visual Editor to the Side' button.

 So I was wondering if this supports PHP file.

**Comment by urin** [comment]
This extension is specifically designed for editing HTML files saved locally, rather than handling the process of generating or creating HTML. Its purpose is to allow users to work with existing static HTML files directly.

However, if you're working within PHP files and including local HTML files, you may be able to leverage this extension to edit those included HTML files. Just note that it won’t support dynamic HTML generation from PHP itself, as it is intended solely for pre-existing HTML files.
